// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElSubmenu: typeof import('element-plus/es')['ElSubMenu'];
  }
}

export {};
